#!/usr/bin/python3
"""
A script that adds all arguments to a Python list, and then save them to a file
"""
import sys
import json
from os import path
save_to_json_file = __import__('5-save_to_json_file').save_to_json_file
load_from_json_file = __import__('6-load_from_json_file').load_from_json_file

filename = "add_item.json"

if not path.exists(filename):
    with open(filename, w, encoding='utf-8') as f:
        json.dump([], f)

try:
    new_list = load-from_json(filename)
except ValueError:
    new_list = []

new_list += sys.argv[1:]

save_to_json(new_list, filename)
